[package]
name = "network"
version = "0.1.0"
authors = ["Adithya Bhat <dth.bht@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt", "net", "sync", "macros", "time"]}